"""initial

Revision ID: a0cbfadf5077
Revises: 
Create Date: 2026-04-16 16:20:40.296434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0cbfadf5077'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('skills_required', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.Column('proposal_draft', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_created_at', 'job_candidates', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_score', 'job_candidates', [sa.literal_column('score DESC')], unique=False)
    op.create_index('ix_status', 'job_candidates', ['status'], unique=False)
    op.create_index('uq_source_source_id', 'job_candidates', ['source', 'source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_source_source_id', table_name='job_candidates')
    op.drop_index('ix_status', table_name='job_candidates')
    op.drop_index('ix_score', table_name='job_candidates')
    op.drop_index('ix_created_at', table_name='job_candidates')
    op.drop_table('job_candidates')
    # ### end Alembic commands ###
